### PR TITLE
Docs - Publishing - Added PowerShell Examples

### PR DESCRIPTION
**Pull request by Joeharrison94**

### CODE REVIEW

**Comment by binwiederhier** [comment]
Your pull request was against the `docs` branch, and it was really really out of date. I manually pulled in the changes and pushed them to main (see https://github.com/binwiederhier/ntfy/commits/main). It looks wonderfully. Thank you.

Next time ensure you are up-to-date locally before creating a branch (`git pull upstream main`).

**Comment by Joeharrison94** [comment]
That's odd as I pulled it just before the edit, but will do! ---- On Fri, 18 Mar 2022 19:06:21 +0000  ***@***.***  wrote ----
Your pull request was against the docs branch, and it was really really out of date. I manually pulled in the changes and pushed them to main (see https://github.com/binwiederhier/ntfy/commits/main). It looks wonderfully. Thank you.
Next time ensure you are up-to-date locally before creating a branch (git pull upstream main).

**Comment by binwiederhier** [comment]
I don't know I think you pulled from `docs` which was many months old.

**Comment by Joeharrison94** [comment]
Ahh sorry about that. ---- On Fri, 18 Mar 2022 20:07:45 +0000  ***@***.***  wrote ----
I don't know I think you pulled from docs which was many months old.

**Comment by binwiederhier** [comment]
No worries. The merge conflicts were easy to solve. You did the hard work.

**Comment by Joeharrison94** [comment]
Anytime, can't see the changes in the docs yet though do you have to restart it to reflect?  ---- On Fri, 18 Mar 2022 20:12:23 +0000  ***@***.***  wrote ----
No worries. The merge conflicts were easy to solve. You did the hard work.

**Comment by binwiederhier** [comment]
The docs are baked into the app, so I'd have to rebuild and create a release for it to show up. I only do that if I have significant changes. So it'll likely be a couple of weeks before it shows up (unless there's something significant before that).

**Pull request closed without merging**
