### PR TITLE
Add Arch Linux installation instructions

### PR DESCRIPTION
**Pull request by arjan-s**
As requested in #63

### CODE REVIEW

**Comment by arjan-s** [comment]
As requested in #63

**Comment by binwiederhier** [comment]
Awesome thanks

**Comment by binwiederhier** [comment]
Does this auto update or do you need to manually update the aur package thingy?

**Comment by arjan-s** [comment]
It depends. If one uses an AUR helper, it will keep the package up to date. If one chooses to install a package manually, updating is up to the user.

**Comment by binwiederhier** [comment]
Oh I should have been more clear, sorry for not knowing this. The PKGBUILD file (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ntfysh-bin), do you have to manually update this on every new version? Cause I iterate quite quickly and I'd like to reduce other people's load, if I can do it or it happens automatically it's probably easier. I don't know how much you mind.

**Comment by arjan-s** [comment]
Oh right! Sorry, I misinterpreted your question.
Updating the PKGBUILD is manual labor (might script it away at some point though). I'm happy to do it, as I use it actively myself and also like to stay up to date on stuff I'm using. But if you prefer maintaining it yourself, I'm happy to surrender maintainership.

**Comment by binwiederhier** [comment]
Nah it's better if someone maintains it that actually knows what they are doing. Just let me know if you stop using it and then I'll jump in. 

Thank youfl for your help!!!

**Pull request merged**
