### PR TITLE
Add Node-RED and Gatus examples.

### PR DESCRIPTION
**Pull request by nickexyz**
I created some examples for Node-RED and Gatus.
Feel free to include them, or not. :)

### CODE REVIEW

**Comment by binwiederhier** [comment]
Thank you!

**Comment by binwiederhier** [comment]
Refined it a bit here: https://github.com/binwiederhier/ntfy/commit/e6f19d050f03aea095e61c12176020e9cb39949b

**Comment by nickexyz** [comment]
Cheers!
I think the collapsed code block broke though, seems like an extra empty line is needed before ```

**Comment by binwiederhier** [comment]
Works on my mkdocs. Maybe it's a version difference. I'll fix it later

**Comment by nickexyz** [comment]
That may be the case, I just checked from the github webui.

**Comment by binwiederhier** [comment]
You should totally show a screenshot of that node red flow. I just looked at the tool and it looks super cool

**Comment by nickexyz** [comment]
Nodered is awesome, great companion to Home Assistant as well!

The flows are pretty basic, so not that much to look at, but I added previews for them.
Something like this you had in mind?
https://github.com/nickexyz/ntfy/blob/docs-noderedupdate/docs/examples.md

**Comment by binwiederhier** [comment]
Very cool yes

**Comment by TwiN** [comment]
FYI I just added a dedicated alerting provider for ntfy on Gatus https://github.com/TwiN/gatus/pull/336

The [configuration](https://github.com/TwiN/gatus#configuring-ntfy-alerts) currently only supports topic, URL and priority, but I might expend it as necessary.

I also had the opportunity to try out ntfy, and you've done awesome work @binwiederhier (and its contributors, of course :)); I love the project!

**Comment by binwiederhier** [comment]
Awesome @TwiN very cool. I'll add it to the docs as officially supported tonight.

**Comment by binwiederhier** [comment]
https://github.com/binwiederhier/ntfy/commit/d989ba0ab01377cebd2f292f75b9a1e257772fe2

If you wanna add an example (https://github.com/binwiederhier/ntfy/blob/main/docs/examples.md) of the config/integration, that'd also be awesome.

**Comment by TwiN** [comment]
@binwiederhier With pleasure, I'll submit a PR shortly :)

**Pull request merged**
