### PR TITLE
user.Manager: fix ACL write, read order

### PR DESCRIPTION
**Pull request by sandman7920**
This should fix `read-only access to topic *` being applied before `read-write access to topic _PREFIX_*` Before this if we have:

```
ntfy access user "mytopic*" rw
ntfy access user "*" ro
```

read-only access rule was applied first and user couldn't write to mytopic*

See #914

### CODE REVIEW

**Comment by sandman7920** [comment]
This PR still does not solve the following case
```
ntfy access user "mytopic*" rw
ntfy access user "mytopic_read_only*" ro
ntfy access user "*" ro
```

The user will still be able to write into `mytopic_read_onlyXXX`

Maybe query should be something like that
```go
selectTopicPermsQuery = `
  SELECT read, write
  FROM user_access a
  JOIN user u ON u.id = a.user_id
  WHERE (u.user = ? OR u.user = ?) AND ? LIKE a.topic ESCAPE '\'
  ORDER BY u.user DESC, LENGTH(a.topic) DESC, a.write DESC
`
```

For each user, we should test in order `THE_LONGEST_RULE`->`WRITE_PERMISSION`

**Comment by binwiederhier** [comment]
Can you add a bunch of unit tests to check these cases? I don't want to just yolo merge this.

**Comment by sandman7920** [comment]
I don't know how fast the `SQLIte`.`LENGTH`  function is, maybe it's reasonable to create a `topic_length` field in `access` table.

**Comment by binwiederhier** [comment]
I would like to apologize for not addressing this earlier. I am looking at your solution now, and I'm trying to understand the root cause. Thank you for the tests and all the work. It is much appreciated!!

**Pull request merged**
