### PR TITLE
add timezone for docker install

### PR DESCRIPTION
**Pull request by ksurl**
add support for timezone

### CODE REVIEW

**Comment by binwiederhier** [comment]
I reverted this change because it fails the build pipeline for ARM. My assumption is that the alpine:latest image is an amd64 image and it cannot run `apk`. I think there is a way to solve this, but for this hotfix release I didn't have time.

Failed pipeline: https://github.com/binwiederhier/ntfy/runs/6718645921?check_suite_focus=true

**Comment by ksurl** [comment]
hmm that's odd. I am using buildx for multi arch builds and my image also has tzdata install with no issues but I am not using goreleaser. just direct docker buildx action.

**Comment by binwiederhier** [comment]
Goreleaser can do buildx apparently. https://goreleaser.com/customization/docker/

And you can set the platform flag too i think.

**Comment by binwiederhier** [comment]
You may be able to do something like this: https://github.com/zinclabs/zinc/blob/main/Dockerfile#L6

**Comment by egooner** [comment]
Any progress on this - using Delay send with absolute time not simple in Docker as it is using UTC and I am not in UTC!! Delay with offset is fine but would be nice to be able to use absolute time also.

**Comment by kruton** [comment]
I was really confused because the docs were not reverted.

**Comment by Ishrathh** [comment]
Time zone can be added using docker-compose, let me know if you would like me to share @egooner @kruton

**Comment by egooner** [comment]
I have the following already set ... but to be honest cannot recall whether this did the trick or not but if I issue date in the console I get this so I think not!!
___
Fri Sep  8 18:46:27 UTC 2023
___
environment:
      - "TZ=Europe/London"
volumes:
      - "/etc/localtime:/etc/localtime:ro"

**Comment by Ishrathh** [comment]
You can check for the correct time zone and there are 2 issues, both the machine running the container as well as the container have to be on the correct time zone. I believe you can manage it for your machine but for the docker instance here are my instructions:

#  docker-compose.yml 
```
version: "2.3"

services:
  ntfy:
    build: . # This will build dockerfile in current dir
    container_name: ntfy
    command:
      - /usr/bin/ntfy
      - serve
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 8080:80
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --no-check-certificate --tries=1 https://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
```

#  Dockerfile
```
# Use the original ntfy image as the base
FROM binwiederhier/ntfy

# Install tzdata and tini packages
RUN apk update && apk add tzdata tini

# Set the timezone
ENV TZ=Asia/Colombo

# Use tini as the entrypoint
ENTRYPOINT ["/sbin/tini", "--"]
```

This is what I used, change the time zone to yours as needed. I also had to use tini which reaps zombie processes that were accumulated by 'ssl_client' process of ntfy. Also note that you can set the time zone in docker-compose as an environment variable OR in the Dockerfile. Dockerfile is easier if you don't plan on changing the time zone often

To check if the time zone of the container is correct you can do the following:
```
# sudo docker exec -it ntfy /bin/sh
# date
```

**Comment by egooner** [comment]
Thanks for that @Ishrathh - I did your docker build example with the exception of the tini which did not seem to work for me!! 
Would be good to see Timezone built into the system rather than having to do this!! @binwiederhier  - any chance of incorporating the tzdata package into the build and supporting passing the TZ in the Environment variable. The solution above works but creates more effort on behalf of the users to do this.

**Comment by Ishrathh** [comment]
Your welcome @egooner, if you would like me to assist you with the setup of tzdata without the tini part let me know :D

> I reverted this change because it fails the build pipeline for ARM. My assumption is that the alpine:latest image is an amd64 image and it cannot run `apk`. I think there is a way to solve this, but for this hotfix release I didn't have time.
> 
> Failed pipeline: https://github.com/binwiederhier/ntfy/runs/6718645921?check_suite_focus=true

@binwiederhier Would be awesome if we can get the time zone released on arch's that support it

**Comment by binwiederhier** [comment]
How are we supposed to do that? Different docker files just because of this? That's seems little ridiculous.

**Comment by egooner** [comment]
Not sure how your build process works @binwiederhier  (not very good on docker build etc) but I spotted this on conditional docker build not sure if it helps. [Docker File Conditions](https://stackoverflow.com/questions/43654656/dockerfile-if-else-condition-with-external-arguments)

**Comment by binwiederhier** [comment]
Re-added for linux/amd64 in https://github.com/binwiederhier/ntfy/commit/8adb9ee633c5cca607892b9ab42b2685fa7fec73, see #894

**Pull request merged**
