### PR TITLE
Linux Distributor

### PR DESCRIPTION
**Pull request by karmanyaahm**
This is the Linux equivalent of binwiederhier/ntfy-android#6

This is not ready for review yet

#9

### CODE REVIEW

**Comment by karmanyaahm** [comment]
Ignoring all the linting, error messages, logging etc. minor bugs, can you comment on the general architecture of this change? I just want to be sure that you're fine with this before going further and doing all that.

**Comment by karmanyaahm** [comment]
The major things this change adds is the UnifiedPush D-Bus distributor library, a SQLite database to store all the UnifiedPush connections (I still need to add a config for the file location for this), and all the logic that handles the unifiedpush subscriptions and message routing.

**Comment by binwiederhier** [comment]
As mentioned in the chat; my apologies for not looking at this earlier. I will get to it tomorrow.

**Comment by binwiederhier** [comment]
Closed for now until there's more interest again to pick this up again :-D

**Pull request closed without merging**
