### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by nimbleghost**
Adds prettier to npm, plus the relevant make targets.

Created a `devDependencies` sections for tooling, and moved react-scripts there too, which is the only other non-production dependency.

This PR needs to be rebased or merged with a merge commit into master, so that the `.git-blame-ignore-refs` file still references a valid commit.

### CODE REVIEW

**Comment by nimbleghost** [comment]
Hmm, depending on what weblate does, perhaps we want to ignore the translations in prettier too.

**Comment by binwiederhier** [comment]
@nimbleghost Just checking, you didn't change anything but the formatting, right? I'm going through the PR but it doesn't look like it.

**Comment by nimbleghost** [comment]
@binwiederhier Correct, just `npm run format` in this PR!

**Comment by binwiederhier** [comment]
It's already merged. I do have to check everything even if it's autogenerated. Due diligence.

**Pull request merged**
