### PR TITLE
Full feature message example

### PR DESCRIPTION
**Pull request by aTable**
Currently, it's not obvious that a multiline message is possible as all the examples are single lines. This change helps bring attention to that however, it does throw the nice language alignment out a bit as this is the only snippet on the whole page that is a bash shell and not direct curl commands.

Ideally, all the supported languages are filled out and not `// TODO` but what are you thoughts to this change?

### CODE REVIEW

**Comment by binwiederhier** [comment]
Thank you for contributing. I love the idea of having another example at the top. We've added many features, so why not use this spot to show some of them. You could, for instance, show 

- multiline
- click action
- action buttons
- delayed delivery 

all in one example. 

What do you think?

**Comment by binwiederhier** [comment]
Sorry for the back and forth, but this is prime real estate in terms of docs, so I want the right example there. Your example was good, but not realistic enough, imho. What do you think of the one below? If you fill out the other languages, I'll provide the image.

"You can also do multi-line messages. Here's an example using a click action, a user action, with an external image attachment and forwarded via email:"

```
curl \
  -H "Click: https://home.nest.com/" \
  -H "Attach: https://nest.com/view/yAxkasd.jpg" \
  -H "Actions: http, Open door, https://api.nest.com/open/yAxkasd, clear=true" \
  -H "Email: phil@example.com" \
  -d "There's someone at the door. 🐶
   
Please check if it's a good boy or a hooman. 
Doggies have been known to ring the doorbell." \
      ntfy.sh/mydoorbell
```

Screenshot_20220504-191014

**Comment by binwiederhier** [comment]
Sorry for the back and forth, but this is prime real estate in terms of docs, so I want the right example there. Your example was good, but not realistic enough, imho. What do you think of the one below? If you fill out the other languages, I'll provide the image.

"You can also do multi-line messages. Here's an example using a click action, a user action, with an external image attachment and forwarded via email:"

```
curl \
  -H "Click: https://home.nest.com/" \
  -H "Attach: https://nest.com/view/yAxkasd.jpg" \
  -H "Actions: http, Open door, https://api.nest.com/open/yAxkasd, clear=true" \
  -H "Email: phil@example.com" \
  -d "There's someone at the door. 🐶
   
Please check if it's a good boy or a hooman. 
Doggies have been known to ring the doorbell." \
      ntfy.sh/mydoorbell
```

Screenshot_20220504-191014

**Comment by aTable** [comment]
No dramas, I like your example. I'm doing this from the web IDE so not certain the language syntax for each example is 100% right

**Comment by binwiederhier** [comment]
That's perfectly alright. I do it from my IDE and I've not tested all of the examples either 😬 so no worries. Just do what you can and I'll do the rest.

**Comment by binwiederhier** [comment]
Awesome. Thanks!

**Pull request merged**
