### PR TITLE
Add version info to web app

### PR DESCRIPTION
**Pull request by nimbleghost**
screenshot

### CODE REVIEW

**Comment by binwiederhier** [comment]
I am actually disagreeing with this one. Exposing the version of any running software on the web makes it easier to fingerprint it for vulnerabilities. That's why nginx et al have options to turn version signatures off. I'd be okay with showing it in dev mode only, which isn't all that useful.

**Comment by nimbleghost** [comment]
I get your point, but it's fairly simple to determine via the bundler version hashing (if you have access to the releases to compare it to).

**Comment by binwiederhier** [comment]
> I get your point, but it's fairly simple to determine via the bundler version hashing (if you have access to the releases to compare it to).

That's true, but let's not make it too easy for the script kiddies.

**Comment by theS1LV3R** [comment]
How about having it be an option? I am using [argus](https://release-argus.io) for monitoring updates to the software I run. Having version information be exposed either over the API or in the GUI would make that monitoring way easier.

**Pull request closed without merging**
